#!/usr/bin/env python
# encoding: utf-8
"""
audiofile3.py

The MIT License (MIT)

Copyright (c) 2013 Matt Ryan

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
"""

from sys import argv, exit

import json

from aflib3 import AFLibrary, AFMongoDataStore
from afutils import get_clargs, find_files_with_ext, parse_query
import afutils.file_pattern as pattern
from afmq import AFMQ

lib = AFLibrary(AFMongoDataStore())

def main(args):
	if args['path']:
		lib.initialize_db()
		afmq = AFMQ('/audiofile/library_additions')
		for f in find_files_with_ext(args['path'], 'mp3'):
			print 'Writing to queue: "%s"' % json.dumps([f, args['path']])
			afmq.put(json.dumps([f, args['path']]))
	elif args['query']:
		qdict = {}
		for key,val in parse_query(args['query'].strip()):
			qdict[key] = val
		for song in lib.get_songs(qdict):
			print song
	elif args['pattern']:
		p = args['pattern']
		if not pattern.is_valid(p):
			print '\'%s\' is not a valid pattern.' % args['pattern']
			exit(1)
		afmq = AFMQ('/audiofile/file_renames')
		for song in lib.get_songs(None):
			afmq.put(json.dumps([song.__dict__, p]))


if __name__ == '__main__':
	main(get_clargs(argv[1:]))

